infra : Deploy docker compose test & ping check in CI action
voyage-plus-1010/cicd pull request #28
Opened 2023-09-14 15:40 UTC by seanlion

- docker compose test 도입
- ping health check

2023-09-14 15:44 UTC, kimseungbin requested changes
환경변수 설정이 안 되어있습니다.

2023-09-14 15:48 UTC, seanlion commented
@kimseungbin port 말씀하신걸까요? name 밑에 env로 적으면 적용되는게 아닌가요?

2023-09-14 15:49 UTC, kimseungbin commented
```
Run docker-compose up -d
The DB_PORT variable is not set. Defaulting to a blank string.
The DB_USERNAME variable is not set. Defaulting to a blank string.
The DB_PASSWORD variable is not set. Defaulting to a blank string.
The DB_NAME variable is not set. Defaulting to a blank string.
The APP_PORT variable is not set. Defaulting to a blank string.
The Compose file './docker-compose.yaml' is invalid because:
services.api.ports contains an invalid type, it should be a number, or an object
services.postgres.ports contains an invalid type, it should be a number, or an object
Error: Process completed with exit code 1.
```

에러 메세지 전체입니다.

2023-09-15 02:33 UTC, kimseungbin commented on .github/workflows/ci.yaml
> +          APP_PORT : 3003
`docker-compose down` 에서 해당 에러가 발생하는 이유는 무어인가요? 직관적이지는 않네요.

2023-09-15 02:39 UTC, kimseungbin approved these changes

2023-09-15 10:21 UTC, merged