infra : server + ci cd integration
voyage-plus-1010/cicd pull request #39
Opened 2023-09-15 12:25 UTC by seanlion

- server 로직 & CI/CD 프로세스 로직 통합

2023-09-15 14:23 UTC, kimseungbin requested changes

2023-09-15 14:23 UTC, kimseungbin commented on Dockerfile
> +RUN cd /tmp/app && npm install
WORKDIR 명령어 참고해주세요.

https://docs.docker.com/engine/reference/builder/#workdir

2023-09-15 14:23 UTC, kimseungbin commented on Dockerfile
> +RUN cp -a /tmp/app/node_modules /usr/src/app
복사 과정 설명이 필요한거같습니다 ㅜㅜ

2023-09-15 14:23 UTC, kimseungbin commented on docker-compose.yaml
> -version: '3'
버전이 누락됐습니다.

2023-09-15 14:23 UTC, kimseungbin commented on package.json
> -		"format:check": "prettier . --check",
포맷 체킹 기능이 누락됐습니다.

2023-09-15 14:23 UTC, kimseungbin commented on package.json
> -		"lint:fix": "ESLINT_USE_FLAT_CONFIG=true eslint . --fix"
린트 픽스 기능이 누락됐습니다.

2023-09-15 14:23 UTC, kimseungbin commented on src/app.module.ts
> +      envFilePath: ['.env'],
.env 를 사용할지 우선 논의가 필요해보입니다.

2023-09-15 14:23 UTC, kimseungbin commented on src/orders/orders.controller.ts
> +  }
```Suggest
  @Post()
  create(@Body() createOrderDto: CreateOrderDto): Promise<Order> {
    return this.ordersService.create(createOrderDto);
  }
```
기본으로 201로 반환되는 POST 를 명시적으로 200으로 고칠 필요는 없습니다.
또한 URI 에 동사를 넣는 것은 RESTful 하지 않습니다.

2023-09-15 14:23 UTC, kimseungbin commented on docker-compose.yaml
> +    image: postgres:alpine
a2667bc8b9b98d0daaa4fe5b7ab087aa75caa1a5
해당 커밋의 변경사항은 내용으로 보건데 `docker-compose.yaml` 을 작성한 것이 아니라 db 이미지 이름을 수정한 것으로 보입니다.

2023-09-15 14:23 UTC, kimseungbin commented on src/app.module.ts
> +/* eslint-disable prettier/prettier */
의도하신 설정인가요?

2023-09-15 14:23 UTC, kimseungbin commented on src/orders/orders.repository.ts
> +/* eslint-disable prettier/prettier */
이부분도 의도하신 설정인가요?

2023-09-15 14:23 UTC, kimseungbin commented on src/orders/orders.repository.ts
> +  private readonly logger: Logger;
6e86c22c2c39f356388acee3ebbe685d2b32cf56
해당 커밋에 전체적으로 포맷팅과 코드 변경사항이 하나로 합쳐져 있습니다.
다음에는 두 작업을 분리해서 커밋하시면 가독성이 높아질 것같습니다.

2023-09-15 14:23 UTC, kimseungbin commented on .github/CODEOWNERS
> +@gong-yeongbin @kimseungbin @seanlion @XPECTER
3eb7d820d19a09a8e2fde4c84b60fc4bd510af07
드랍해도 되지 않을까요?

2023-09-15 14:23 UTC, kimseungbin commented on .gitignore
> +.vscode/launch.json
위의 `.vscode/*` 가 포함하지 않나요?

2023-09-15 14:23 UTC, kimseungbin commented on .github/workflows/ci.yml
이미 main 에 병합되어있기도하고 보안 취약점이 알려진 버전이라 해당 레포지토리에 사용자제가 안내되어 있기 때문에 사용하지 않는 것이 좋을것같습니다.

2023-09-15 14:23 UTC, kimseungbin commented on .github/workflows/ci.yaml
> +        node-version: [ 16.x ]
a4917b49ba7b0befa078f678975d5ef9f4dc847e
해당 커밋 제목과는 상관없는 변경사항인 것같은데, 기왕이면 lts 에서 테스트하는 것이 적합해보입니다.

2023-09-15 14:23 UTC, kimseungbin commented on .github/workflows/aws.yaml
> +
PR 이 병합되기 전에 검사하는게 적합해보입니다. 이미 병합한 후에 검사할 필요는 없어보입니다.

2023-09-15 14:23 UTC, kimseungbin commented on package.json
> +    "env-cmd": "^10.1.0",
혹시 어떤 역할을 하나요?

2023-09-15 14:32 UTC, XPECTER submitted a review, later dismissed

2023-09-15 15:06 UTC, seanlion commented on .prettierrc
> -	"bracketSpacing": true,
그건 개인적으로 테스트해보겠습니다.
저희 작업엔 넣을 생각은 없었습니다.

2023-09-15 15:07 UTC, seanlion commented on .eslintrc.js
이건 수정해놓겠습니다.

2023-09-15 15:07 UTC, seanlion commented on .prettierrc
> +  "semi": true,
semicolon 넣는거 말씀하시는거죠? 저는 넣는걸 선호하긴하는데 우선은 시간 상 제외해놓을게요.

2023-09-15 15:08 UTC, XPECTER commented on .prettierrc
> +  "semi": true,
저는 세미콜론을 전부 사용합니다.

2023-09-15 15:08 UTC, seanlion commented on Dockerfile
> +FROM node:18.17.0-alpine
그러면 그냥 alpine을 쓰는거로 하겠습니다!

2023-09-15 15:08 UTC, seanlion commented on .vscode/launch.json
이거 gitignore에 설정해놓았는데 안 올리는 방법이 있나요?.. 
지워야 하나

2023-09-15 15:09 UTC, seanlion commented on .vscode/settings.json
위의 질문과 동일한 질문이라 위 대화에서 처리하겠습니다.

2023-09-15 15:11 UTC, kimseungbin commented on .vscode/launch.json
이미 넣은 상태에서 추가하신게 아닐까요?

2023-09-15 15:44 UTC, seanlion commented on Dockerfile
> +RUN apk add --no-cache bash
기존에 사용했던 스크립트인데, bash shell 설치해서 그거로 패키지 설치하는 용도로 사용했었습니다.

2023-09-15 15:44 UTC, seanlion commented on Dockerfile
> +RUN npm i -g @nestjs/cli typescript ts-node
dependency 를 사용하는 방법이 구체적으로 무엇인가요? 
이전에 개인적으로 할 때는 Dockerfile 레퍼런스를 보고 설치하는 식으로 했었어서 비슷하게 작성했습니다.

2023-09-15 15:46 UTC, seanlion commented on Dockerfile
> +RUN cd /tmp/app && npm install
WORKDIR을 /usr/src/app으로 정했었는데, 초반에 WORKDIR로 설정하는게 나을까요?

2023-09-15 15:46 UTC, seanlion commented on Dockerfile
> +RUN cp -a /tmp/app/node_modules /usr/src/app
이 부분 사실 npm install 하면 필요없는 것 같습니다 ㅠ 지워놓을게요

2023-09-15 15:47 UTC, seanlion commented on docker-compose.yaml
> -version: '3'
앗 그렇네요. 추가해놓겠습니다.

2023-09-15 15:49 UTC, kimseungbin commented on Dockerfile
> +RUN apk add --no-cache bash
이제는 패키지 설치가 따로 없죠?

2023-09-15 15:49 UTC, kimseungbin commented on Dockerfile
> +RUN cd /tmp/app && npm install
네 tmp dir 를 따로 쓰지 않아도 되는 장점이 있을 것같습니다.

2023-09-15 15:49 UTC, seanlion commented on src/app.module.ts
> +      envFilePath: ['.env'],
그렇다면, 저는 제출 시간 상 논의가 필요한 부분은 선머지 후논의 같은 방법을 제안합니다.
결론을 내리고 후조치 하는게 좋을 것 같아요

2023-09-15 15:51 UTC, seanlion commented on package.json
> -		"format:check": "prettier . --check",
네 이 부분은 추가해놓겠습니다.

2023-09-15 15:51 UTC, seanlion commented on package.json
> -		"lint:fix": "ESLINT_USE_FLAT_CONFIG=true eslint . --fix"
이 부분도 추가해놓겠습니다.

2023-09-15 15:52 UTC, kimseungbin commented on src/app.module.ts
> +      envFilePath: ['.env'],
네 그런 경우에는 이슈만 생성하고 대화를 해결하면 될거같아요.

2023-09-15 15:53 UTC, seanlion commented on src/orders/orders.controller.ts
> +  }
200으로 고칠 필요가 없다는 건 동의합니다. 수정해놓을게요.
Restful하지 않은 URI이다 이건 저는 이번 리뷰에서 진행하기에는 길어질 수 있는 주제라고 생각합니다.(일단 RESTful에 대해서도 서로 알고 있는게 다를거라고 생각해서)

최소한의 주제(CI/CD 파이프라인이 잘 동작하는가)로 리뷰를 진행하는게 좋을 것 같아서, 서버 코드는 최대한 안 건드리는게 좋다고 생각해요.

2023-09-15 15:54 UTC, gong-yeongbin submitted a review, later dismissed

2023-09-15 15:55 UTC, seanlion commented on docker-compose.yaml
> +    image: postgres:alpine
db 이미지, 볼륨 이름을 바꾸긴 했습니다. 
yaml파일을 수정한거긴한데 커밋의 이름을 아예 바꾸는게 좋다고 생각하시나요?

2023-09-15 15:56 UTC, seanlion commented on src/orders/orders.repository.ts
> +/* eslint-disable prettier/prettier */
이건 테스트할 때 방해되서 적어놓았다가 제거했었는데, 다 제거가 안 된 것 같네요. 제거해놓겠습니다.

2023-09-15 15:57 UTC, seanlion commented on src/orders/orders.repository.ts
> +  private readonly logger: Logger;
네 커밋 쪼개는건 계속 개인적으로 더 연습해야하는 부분일 것 같습니다.

2023-09-15 15:57 UTC, kimseungbin commented on src/orders/orders.repository.ts
> +/* eslint-disable prettier/prettier */
outdated 인 것을 보면 제거가 된 상태로 보입니다.
커밋에 추가할 필요가 없었던 부분이네요.

2023-09-15 15:57 UTC, seanlion commented on .github/CODEOWNERS
> +@gong-yeongbin @kimseungbin @seanlion @XPECTER
이 커밋만 중간에 드랍하려면 interactive rebase 같은걸 해야하나요?

2023-09-15 16:00 UTC, seanlion commented on .github/workflows/ci.yml
ci.yml 파일은 지웠는데 살아있는건가요?..

2023-09-15 16:01 UTC, seanlion commented on .github/workflows/ci.yaml
> +        node-version: [ 16.x ]
이것도 결국 일부분 커밋 쪼개기가 안 된 것 같네요. 근데 말씀하신대로 18.x로 하는게 더 적합해보입니다.

2023-09-15 16:01 UTC, seanlion commented on .github/workflows/aws.yaml
> +
네 그런것 같네요. 별도로 yaml 작성해서 pull request trigger에 실행하는거로 쪼개놓을게요

2023-09-15 16:02 UTC, seanlion commented on package.json
> +    "env-cmd": "^10.1.0",
e2e test 파일 실행할때 사용됩니다

2023-09-15 16:08 UTC, seanlion commented on .eslintrc.js
근데 이거 수정 방향이 eslintrc.js 파일을 지우고, eslint.config.js를 참조한다는게 어떤 방법인가요?

2023-09-15 16:09 UTC, XPECTER commented on .prettierrc
> -	"bracketSpacing": true,
저도 있었으면 좋겠습니다

2023-09-15 16:10 UTC, XPECTER commented on src/app.module.ts
> +      envFilePath: ['.env'],
네 이건 후조치 하는 것으로 확인했습니다

2023-09-15 16:10 UTC, kimseungbin commented on .eslintrc.js
`eslintrc.js` 에서 `eslint.config.js` 로 설정 파일 기준이 바뀌는 중입니다.
제가 전에 올렸던 #32 에서 해당 파일을 추가할 때 주석을 첨부하여 자세하게 설명을 넣어놨었습니다.

2023-09-15 16:15 UTC, kimseungbin commented on .github/workflows/ci.yml
삭제 전에 합쳐져서 outdated 인 상태로 떴습니다.

2023-09-15 16:21 UTC, kimseungbin commented on docker-compose.yaml
> +    image: postgres:alpine
네 그게 더 정확해보입니다.
사실 볼륨 이미지 바꾸는 것은 큰 변경사항은 아니지만 db 버전 변경은 큰 변경사항이니깐요.

2023-09-15 16:21 UTC, kimseungbin commented on .github/CODEOWNERS
> +@gong-yeongbin @kimseungbin @seanlion @XPECTER
앗 젯브레인은 그냥 해주...
제가해서 올려놓을게요.

2023-09-15 16:23 UTC, kimseungbin commented on .github/workflows/aws.yaml
> +
기존에 삭제하신 pull-request.yaml 을 살리는게 더 빠를것같습니다.

2023-09-15 16:31 UTC, seanlion commented on .eslintrc.js
https://github.com/voyage-plus-1010/cicd/pull/39/commits/38a701f236f9381f2491fba35de43e1a0f20a3cc
https://github.com/voyage-plus-1010/cicd/pull/39/commits/08f029e2cb132f2d63ebd549f9b65a20d1c83382

2개 커밋으로 변경사항 반영했습니다.

2023-09-15 16:32 UTC, seanlion commented on .github/workflows/aws.yaml
> +
이 코멘트를 못보고 추가 파이프라인을 수정해놓았습니다.
https://github.com/voyage-plus-1010/cicd/pull/39/commits/1fe717d3fe789c8a17ef7fd47bbe7de49d98b6c2

2023-09-15 16:33 UTC, seanlion commented on .github/workflows/aws.yaml
> +
추가 파이프라인을 수정해놓았습니다.
https://github.com/voyage-plus-1010/cicd/commit/1fe717d3fe789c8a17ef7fd47bbe7de49d98b6c2

2023-09-15 16:39 UTC, seanlion commented on .prettierrc
> -	"bracketSpacing": true,
이건 추가 논의하는거로 하겠습니다!

2023-09-17 14:54 UTC, seanlion commented on Dockerfile
> +RUN npm i -g @nestjs/cli typescript ts-node
해당 커맨드 안 쓰는 방향으로 수정 완료

2023-09-17 14:55 UTC, seanlion commented on docker-compose.yaml
> +    image: postgres:alpine
다음에 작업 진행할때는 커밋 작업 범위와 이름을 좀 더 정확하게 매칭시켜보겠습니다

2023-09-17 14:55 UTC, seanlion commented on Dockerfile
> +RUN cd /tmp/app && npm install
WORKDIR 수정 완료

2023-09-18 01:13 UTC, kimseungbin approved these changes

2023-09-18 02:30 UTC, XPECTER approved these changes

2023-09-18 13:40 UTC, merged